export const popupCopy = {
  title: 'Idle trigger + local game host',
  lede:
    'Firefox-only local game host. After Firefox detects idle, renewed activity reopens the active game surface. The runtime stays extension-owned and nothing is sent anywhere.',
  intervalLabel: 'Idle interval',
  intervalOptions: [
    { value: 60, label: '1 min' },
    { value: 120, label: '2 min' },
    { value: 300, label: '5 min' },
    { value: 600, label: '10 min' },
  ],
  status: {
    armedReady: 'Armed. Firefox is waiting for the next idle period.',
    waitingForActivity: (surface: string) => `Idle detected. The next return to activity will open or refocus the ${surface}.`,
    surfaceOpen: (surface: string) => `The ${surface} is open. The next idle → activity cycle will refocus it.`,
    disarmed: 'Disarmed. Idle triggers are paused.',
  },
  labels: {
    mode: 'Trigger mode',
    pane: 'Game surface',
    awaitingActivity: 'Awaiting activity',
    lastTrigger: 'Last trigger / open',
  },
  runtime: {
    title: 'Runtime host',
    statusLabel: 'Runtime status',
    resumeLabel: 'Resume count',
    checkpointLabel: 'Last checkpoint',
    unavailable: 'No host session yet',
  },
  buttons: {
    arm: 'Arm idle trigger',
    demo: 'Open current surface',
    fullTab: 'Open full tab',
    disarm: 'Pause trigger',
    reset: 'Clear state',
  },
  helper: 'Clear state closes any open surface and removes both the idle trigger checkpoint and the saved runtime host session.',
  notYet: 'Not yet',
  armed: 'Armed',
  disarmed: 'Paused',
  popupWindow: 'Popup window',
  fullTab: 'Full tab',
  closed: 'Closed',
  yes: 'Yes',
  no: 'No',
} as const
