export const runtimeFrameCopy = {
  eyebrow: 'Burger session runtime',
  title: 'Local burger-level session',
  lede:
    'This child runtime now owns a real local-only burger session state tree. It stays single-player, offline, and checkpointable inside the extension host.',
  sessionStatus: 'Runtime state',
  booting: 'Waiting for host boot…',
  phasePrefix: 'Phase',
  locationItems: [
    { id: 'storage', label: 'Storage' },
    { id: 'grill', label: 'Grill' },
    { id: 'board', label: 'Board' },
    { id: 'counter', label: 'Counter' },
  ],
  labels: {
    tick: 'Kitchen tick',
    score: 'Score',
    location: 'Player station',
    heldItem: 'Held item',
    order: 'Active order',
    grill: 'Grill state',
    board: 'Assembly board',
    pantry: 'Pantry stock',
  },
  logTitle: 'Runtime events',
  completionTitle: 'Burger loop complete',
  completionServed: 'The first local burger order was served and checkpointed successfully.',
  completionFailed: 'The burger order timed out. Reset and try the loop again.',
  readyServed: 'Burger session complete and ready to checkpoint.',
  readyFailed: 'Burger session ended after the order timer expired.',
  emptyValue: 'empty',
  buttons: {
    interact: 'Interact',
    tick: 'Advance tick',
    reset: 'Reset session',
  },
  phaseLabels: {
    booting: 'Booting the burger session…',
    running: 'Burger session running locally.',
    paused: 'Burger session paused by the host.',
    completed: 'Burger session complete.',
  },
  pausedStatus: 'Runtime paused. Waiting for the host to resume.',
  capabilities: ['checkpoint', 'pause', 'resume', 'local-session'],
} as const
